config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets, except: [:edit, :update]
  root "tweets#index"

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"

  post "/users/:id/follow", to: "users#follow", as: "follow_user"
  post "/users/:id/unfollow", to: "users#unfollow", as: "unfollow_user"

  # get "/users/:id/followers" => "users#follow"
  # get "/users/:id/followees" => "users#"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"
  belongs_to :followee, foreign_key: :followee, class_name: "User"

  # has_many :tweets, class_name: "Follow", foreign_key: "follower_id"

  # validates :follower_id, uniqueness: { scope: :followee_id }
  # validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_many :tweets

  has_many :followed_users, foreign_key: :follower_id, class_name: "Follow"
  has_many :followees, through: :followed_users, source: :followee
  has_many :following_users, foreign_key: :followee_id, class_name: "Follow"
  has_many :followers, through: :following_users, source: :follower

  validates :user_name, uniqueness: { case_sensitive: true }
  validates :user_name, presence: true
  validates :name, presence: true
  validates :location, presence: true
  validates :bio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 
  def authenticate_user
    redirect_to '/login', status: :see_other unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end
 
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :asc)
    render template: "tweets/index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @users = User.all
    render template: "users/index"
  end

  def show
    @user = User.find_by(id: params[:id])
    render template: "users/show"
  end

  def edit
    @user = User.find_by(id: params[:id])
    render template: "users/edit"
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.image = params[:user][:image]
    if @user.save
      render json: { message: "User created successfully" }, status: :created
    else
      render json: { errors: @user.errors.full_messages }, status: :bad_request
    end
    redirect_to "/users"
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to "/users", status: :see_other
  end

  def follow
    @user = User.find_by(id: params[:id])
    current_user.followees << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end

  def followers
    @user = User.find_by(id: params[:id])
    render @user.followers
  end

  def followees
    @user = User.find_by(id: params[:id])
    render @user.followees
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterCloneFullstack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets</h1>
<% @tweets.each do |tweet| %>
  <h2><%= @tweet.user %></h2>
  <p>text: <%= tweet.text %></p>
  <%= link_to "User", user %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/users/index.html.erb
<h1>All users</h1>
<% @users.each do |user| %>
  <h2><%= user.name %></h2>
  <p>email: <%= user.email %></p>
  <p>image: <%= user.image %></p>
  <%= link_to "More Info", user %>
<% end %>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User info</h1>
<h2><%= @user.name %></h2>
<p>email: <%= @user.email %></p>
<p>image: <%= @user.image %></p>
<!--<p>followers: <%= @user.followers.length %></p>
<p>followees: <%= @user.followees.length %></p> -->

<h3>Followers:</h3>
<p><%= @user.followers.length %></p>
<% @user.followers.each do |follower|%>
<p><%=follower.name%></p>
<% end %>

<h3>Followees:</h3>
<p><%= @user.followees.length %></p>
<% @user.followees.each do |followee|%>
<p><%=followee.name%></p>
<% end %>

<h3>Followee tweets</h3>
<% @user.followees.each do |followee|%>
<p><%=followee.name%></p>
<p><%=followee.tweets.text%></p>
<% end %>

<a href="/users">Back to all users</a>
<%= link_to "Edit user", edit_user_path(@user) %>
<%= link_to "Destroy user", user_path(@user), data: {turbo_method: :delete} %>
<br>
<section id="all-links">
    <% if @user.id == current_user.id %>
        <%= button_to "Logout", '/logout', method: :post %>
    <% elsif current_user.followees.include?(@user) %>
        <h5><%= button_to "Unfollow", unfollow_user_path, method: "POST" %></h5>
    <% else %>
        <h5><%= button_to "Follow", follow_user_path, method: "POST"  %></h5>
    <% end%>
    <%#= link_to 'Followers', user_followers_path(@user) %>
    <%#= link_to 'Following', user_followees_path(@user) %>
    <br>
</section>